/**
 * ---------------------------------------------------------------------------------
 * This file has been generated by Sanity TypeGen.
 * Command: `sanity typegen generate`
 *
 * Any modifications made directly to this file will be overwritten the next time
 * the TypeScript definitions are generated. Please make changes to the Sanity
 * schema definitions and/or GROQ queries if you need to update these types.
 *
 * For more information on how to use Sanity TypeGen, visit the official documentation:
 * https://www.sanity.io/docs/sanity-typegen
 * ---------------------------------------------------------------------------------
 */

export declare const internalGroqTypeReferenceTo: unique symbol;

type ArrayOf<T> = Array<
  T & {
    _key: string;
  }
>;

// Source: schema.json
export type SanityFileAssetReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "sanity.fileAsset";
};

export type LinkFile = {
  asset?: SanityFileAssetReference;
  media?: unknown; // Unable to locate the referenced type "media" in schema
  _type: "file";
};

export type VideoSettings = {
  autoplay?: boolean;
  controls?: boolean;
};

export type SlideVideoSettings = {
  autoplay?: boolean;
  controls?: boolean;
};

export type User = {
  id?: number;
  username?: string;
  permalink_url?: string;
};

export type SanityImageAssetReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
};

export type Slide = {
  _type: "slide";
  type?: "image" | "video";
  video?: MuxVideo;
  image?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
  videoSettings?: SlideVideoSettings;
};

export type SeoPage = {
  _type: "seo.page";
  title?: PlaceholderString;
  description?: string;
  image?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
};

export type SeoSingletons = {
  _type: "seo.singletons";
  title?: string;
  description?: string;
  image?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
};

export type SanityImageCrop = {
  _type: "sanity.imageCrop";
  top?: number;
  bottom?: number;
  left?: number;
  right?: number;
};

export type SanityImageHotspot = {
  _type: "sanity.imageHotspot";
  x?: number;
  y?: number;
  height?: number;
  width?: number;
};

export type SeoFallback = {
  _type: "seo.fallback";
  title?: string;
  description?: string;
  image?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
};

export type PlaceholderString = string;

export type ModuleText = {
  _type: "module.text";
  text?: RichText;
};

export type ModuleMedia = {
  _type: "module.media";
  type?: "image" | "video";
  video?: MuxVideo;
  image?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
  videoSettings?: VideoSettings;
  caption?: string;
};

export type ModuleHeroSlider = {
  _type: "module.heroSlider";
  slides?: Array<
    {
      _key: string;
    } & ModuleHeroEntry
  >;
};

export type PersonReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "person";
};

export type VenueReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "venue";
};

export type ShowReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "show";
};

export type SetReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "set";
};

export type ArticleReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "article";
};

export type ModuleHeroEntry = {
  _type: "module.heroEntry";
  type?: "page" | "custom";
  title?: string;
  text?: RichText;
  link?: OptionalLink;
  contentReference?:
    | PersonReference
    | VenueReference
    | ShowReference
    | SetReference
    | ArticleReference;
};

export type ModuleContentReferenceSlider = {
  _type: "module.contentReferenceSlider";
  title?: string;
  type?: "pool" | "sets" | "shows" | "words";
  style?: "image" | "cards" | "thumbnails";
  count?: 3 | 6 | 9 | 12 | 16;
  poolContentType?: "all" | "persons" | "venues";
  pool?: Array<
    | ({
        _key: string;
      } & PersonReference)
    | ({
        _key: string;
      } & VenueReference)
  >;
  articles?: Array<
    {
      _key: string;
    } & ArticleReference
  >;
  shows?: Array<
    {
      _key: string;
    } & ShowReference
  >;
  sets?: Array<
    {
      _key: string;
    } & SetReference
  >;
  autoLoad?: boolean;
  showTags?: boolean;
};

export type ModuleContentReferenceGrid = {
  _type: "module.contentReferenceGrid";
  title?: string;
  type?: "pool" | "sets" | "shows" | "words";
  poolContentType?: "all" | "persons" | "venues";
};

export type ModuleCarousel = {
  _type: "module.carousel";
  slides?: Array<
    {
      _key: string;
    } & Slide
  >;
};

export type Modules = Array<
  | ({
      _key: string;
    } & ModuleContentReferenceGrid)
  | ({
      _key: string;
    } & ModuleContentReferenceSlider)
  | ({
      _key: string;
    } & ModuleHeroEntry)
  | ({
      _key: string;
    } & ModuleHeroSlider)
  | ({
      _key: string;
    } & ModuleText)
>;

export type LinkFunctions = "cookie";

export type HomeReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "home";
};

export type PoolReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "pool";
};

export type ShowsArchiveReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "showsArchive";
};

export type TimetableReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "timetable";
};

export type WordsReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "words";
};

export type PageReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "page";
};

export type CategoryReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "category";
};

export type CategorySubReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "category.sub";
};

export type TagArticleReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "tag.article";
};

export type TagCraftsReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "tag.crafts";
};

export type TagCityReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "tag.city";
};

export type TagGenreReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "tag.genre";
};

export type TagGlobalReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "tag.global";
};

export type TagVenueReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "tag.venue";
};

export type TagMusicianReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "tag.musician";
};

export type TagServiceReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "tag.service";
};

export type TagMoodReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "tag.mood";
};

export type TagSubGenreReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "tag.subGenre";
};

export type OptionalLink = {
  _type: "optionalLink";
  type?: "none" | "internal" | "external" | "function";
  title?: string;
  reference?:
    | HomeReference
    | PoolReference
    | ShowsArchiveReference
    | TimetableReference
    | WordsReference
    | PersonReference
    | ArticleReference
    | PageReference
    | ShowReference
    | SetReference
    | VenueReference
    | CategoryReference
    | CategorySubReference
    | TagArticleReference
    | TagCraftsReference
    | TagCityReference
    | TagGenreReference
    | TagGlobalReference
    | TagVenueReference
    | TagMusicianReference
    | TagServiceReference
    | TagMoodReference
    | TagSubGenreReference;
  url?: string;
  blank?: boolean;
  func?: LinkFunctions;
};

export type Link = {
  _type: "link";
  type?: "internal" | "external" | "function";
  title?: string;
  reference?:
    | HomeReference
    | PoolReference
    | ShowsArchiveReference
    | TimetableReference
    | WordsReference
    | PersonReference
    | ArticleReference
    | PageReference
    | ShowReference
    | SetReference
    | VenueReference
    | CategoryReference
    | CategorySubReference
    | TagArticleReference
    | TagCraftsReference
    | TagCityReference
    | TagGenreReference
    | TagGlobalReference
    | TagVenueReference
    | TagMusicianReference
    | TagServiceReference
    | TagMoodReference
    | TagSubGenreReference;
  url?: string;
  blank?: boolean;
  func?: LinkFunctions;
};

export type RichTextMedia = Array<
  | {
      children?: Array<{
        marks?: Array<string>;
        text?: string;
        _type: "span";
        _key: string;
      }>;
      style?: "normal" | "h1" | "h2" | "h3" | "h4" | "h5" | "h6" | "blockquote";
      listItem?: "bullet" | "number";
      markDefs?: Array<{
        type?: "internal" | "external" | "download" | "function";
        reference?:
          | HomeReference
          | PoolReference
          | ShowsArchiveReference
          | TimetableReference
          | WordsReference
          | PersonReference
          | ArticleReference
          | PageReference
          | ShowReference
          | SetReference
          | VenueReference
          | CategoryReference
          | CategorySubReference
          | TagArticleReference
          | TagCraftsReference
          | TagCityReference
          | TagGenreReference
          | TagGlobalReference
          | TagVenueReference
          | TagMusicianReference
          | TagServiceReference
          | TagMoodReference
          | TagSubGenreReference;
        url?: string;
        blank?: boolean;
        file?: LinkFile;
        func?: LinkFunctions;
        _type: "link";
        _key: string;
      }>;
      level?: number;
      _type: "block";
      _key: string;
    }
  | ({
      _key: string;
    } & ModuleMedia)
  | ({
      _key: string;
    } & ModuleCarousel)
>;

export type RichText = Array<{
  children?: Array<{
    marks?: Array<string>;
    text?: string;
    _type: "span";
    _key: string;
  }>;
  style?: "normal" | "h1" | "h2" | "h3" | "h4" | "h5" | "h6" | "blockquote";
  listItem?: "bullet" | "number";
  markDefs?: Array<{
    type?: "internal" | "external" | "download" | "function";
    reference?:
      | HomeReference
      | PoolReference
      | ShowsArchiveReference
      | TimetableReference
      | WordsReference
      | PersonReference
      | ArticleReference
      | PageReference
      | ShowReference
      | SetReference
      | VenueReference
      | CategoryReference
      | CategorySubReference
      | TagArticleReference
      | TagCraftsReference
      | TagCityReference
      | TagGenreReference
      | TagGlobalReference
      | TagVenueReference
      | TagMusicianReference
      | TagServiceReference
      | TagMoodReference
      | TagSubGenreReference;
    url?: string;
    blank?: boolean;
    file?: LinkFile;
    func?: LinkFunctions;
    _type: "link";
    _key: string;
  }>;
  level?: number;
  _type: "block";
  _key: string;
}>;

export type FallbackContentLocalized = {
  _type: "fallback.contentLocalized";
  title?: InternationalizedArrayString;
  description?: InternationalizedArrayRichText;
  image?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
};

export type FallbackContent = {
  _type: "fallback.content";
  title?: string;
  description?: RichText;
  image?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
};

export type FallbackGlobal = {
  _id: string;
  _type: "fallbackGlobal";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  fallbackArticle?: FallbackContentLocalized;
  fallbackPerson?: FallbackContentLocalized;
  fallbackSet?: FallbackContent;
  fallbackShow?: FallbackContent;
  fallbackVenue?: FallbackContentLocalized;
};

export type InternationalizedArrayRichText = Array<
  {
    _key: string;
  } & InternationalizedArrayRichTextValue
>;

export type InternationalizedArrayString = Array<
  {
    _key: string;
  } & InternationalizedArrayStringValue
>;

export type SiteSettings = {
  _id: string;
  _type: "siteSettings";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
  favicon?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
  seo?: SeoFallback;
};

export type SiteNav = {
  _id: string;
  _type: "siteNav";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  mainMenu?: Array<
    {
      _key: string;
    } & Link
  >;
  schedulePage?: TimetableReference;
  discordLink?: string;
  footerMenu?: Array<
    {
      _key: string;
    } & Link
  >;
};

export type SiteCookieBanner = {
  _id: string;
  _type: "siteCookieBanner";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  useCookieBanner?: boolean;
  consentModal?: {
    description?: string;
    acceptAllBtn?: string;
    acceptNecessaryBtn?: string;
    showPreferencesBtn?: string;
  };
  preferencesModal?: {
    title?: string;
    acceptAllBtn?: string;
    acceptNecessaryBtn?: string;
    savePreferencesBtn?: string;
    sections?: Code;
  };
};

export type Code = {
  _type: "code";
  language?: string;
  filename?: string;
  code?: string;
  highlightedLines?: Array<number>;
};

export type Error = {
  _id: string;
  _type: "error";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
  content?: RichText;
  button?: string;
};

export type InternationalizedArrayRichTextMediaValue = {
  _type: "internationalizedArrayRichTextMediaValue";
  value?: RichTextMedia;
  language?: string;
};

export type InternationalizedArrayRichTextValue = {
  _type: "internationalizedArrayRichTextValue";
  value?: RichText;
  language?: string;
};

export type InternationalizedArrayStringValue = {
  _type: "internationalizedArrayStringValue";
  value?: string;
  language?: string;
};

export type InternationalizedArrayRichTextMedia = Array<
  {
    _key: string;
  } & InternationalizedArrayRichTextMediaValue
>;

export type Home = {
  _id: string;
  _type: "home";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
  modules?: Modules;
  seo?: SeoPage;
  color?: Color;
};

export type Color = {
  _type: "color";
  hex?: string;
  alpha?: number;
  hsl?: HslaColor;
  hsv?: HsvaColor;
  rgb?: RgbaColor;
};

export type Pool = {
  _id: string;
  _type: "pool";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
  slider?: {
    autoLoad?: boolean;
    profiles?: ArrayOf<PersonReference | VenueReference>;
  };
  modules?: Modules;
  seo?: SeoPage;
  color?: Color;
};

export type ShowsArchive = {
  _id: string;
  _type: "showsArchive";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
  slider?: {
    autoLoad?: boolean;
    sets?: Array<
      {
        _key: string;
      } & SetReference
    >;
  };
  modules?: Modules;
  seo?: SeoPage;
  color?: Color;
};

export type Timetable = {
  _id: string;
  _type: "timetable";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
  backgroundImage?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
  modules?: Modules;
  seo?: SeoPage;
  color?: Color;
};

export type Words = {
  _id: string;
  _type: "words";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
  slider?: {
    autoLoad?: boolean;
    articles?: Array<
      {
        _key: string;
      } & ArticleReference
    >;
  };
  modules?: Modules;
  seo?: SeoPage;
  color?: Color;
};

export type Person = {
  _id: string;
  _type: "person";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
  slug?: Slug;
  image?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
  description?: InternationalizedArrayRichText;
  tags?: ArrayOf<
    | TagCraftsReference
    | TagGlobalReference
    | TagSubGenreReference
    | TagCityReference
    | TagMusicianReference
    | TagServiceReference
  >;
  contact?: string;
  socials?: {
    instagram?: string;
    soundcloud?: string;
    nina?: string;
    bandcamp?: string;
    web?: string;
  };
  modules?: Modules;
  venues?: Array<
    {
      _key: string;
    } & VenueReference
  >;
  shows?: Array<
    {
      _key: string;
    } & ShowReference
  >;
  poolVisibility?: boolean;
  seo?: SeoPage;
};

export type Article = {
  _id: string;
  _type: "article";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
  slug?: Slug;
  datetime?: string;
  image?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
  socials?: {
    instagram?: string;
    soundcloud?: string;
    nina?: string;
    bandcamp?: string;
    web?: string;
  };
  text?: InternationalizedArrayRichTextMedia;
  useTeaserText?: boolean;
  textTeaser?: InternationalizedArrayRichText;
  contentReferences?: ArrayOf<PersonReference | ShowReference | VenueReference>;
  modules?: Modules;
  autoRelatedArticles?: boolean;
  relatedArticles?: Array<
    {
      _key: string;
    } & ArticleReference
  >;
  tags?: ArrayOf<
    | TagGlobalReference
    | TagArticleReference
    | TagCityReference
    | TagSubGenreReference
  >;
  seo?: SeoPage;
};

export type Page = {
  _id: string;
  _type: "page";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
  slug?: Slug;
  content?: InternationalizedArrayRichTextMedia;
  modules?: Modules;
  seo?: SeoPage;
};

export type Show = {
  _id: string;
  _type: "show";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
  slug?: Slug;
  image?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
  content?: RichTextMedia;
  sets?: Array<
    {
      _key: string;
    } & SetReference
  >;
  socials?: {
    instagram?: string;
    soundcloud?: string;
    nina?: string;
    bandcamp?: string;
    web?: string;
  };
  persons?: Array<
    {
      _key: string;
    } & PersonReference
  >;
  venues?: Array<
    {
      _key: string;
    } & VenueReference
  >;
  tags?: ArrayOf<TagGlobalReference | TagSubGenreReference | TagCityReference>;
  seo?: SeoPage;
};

export type Set = {
  _id: string;
  _type: "set";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
  clickableTitle?: boolean;
  slug?: Slug;
  additionalTitle?: string;
  imageLink?: string;
  image?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
  soundcloud?: Soundcloud;
  content?: RichTextMedia;
  persons?: Array<
    {
      _key: string;
    } & PersonReference
  >;
  venues?: Array<
    {
      _key: string;
    } & VenueReference
  >;
  tracklistSingleTrack?: boolean;
  tracklist?: Array<string>;
  tracklistRich?: RichText;
  tags?: ArrayOf<TagGlobalReference | TagSubGenreReference | TagCityReference>;
  datetime?: string;
  seo?: SeoPage;
};

export type MuxVideoAssetReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "mux.videoAsset";
};

export type MuxVideo = {
  _type: "mux.video";
  asset?: MuxVideoAssetReference;
};

export type Venue = {
  _id: string;
  _type: "venue";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
  slug?: Slug;
  image?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
  description?: InternationalizedArrayRichText;
  tags?: ArrayOf<
    | TagGlobalReference
    | TagSubGenreReference
    | TagCityReference
    | TagServiceReference
    | TagVenueReference
  >;
  contact?: string;
  socials?: {
    instagram?: string;
    soundcloud?: string;
    nina?: string;
    bandcamp?: string;
    web?: string;
  };
  modules?: Modules;
  poolVisibility?: boolean;
  shows?: Array<
    {
      _key: string;
    } & ShowReference
  >;
  persons?: Array<
    {
      _key: string;
    } & PersonReference
  >;
  seo?: SeoPage;
};

export type TagSubGenre = {
  _id: string;
  _type: "tag.subGenre";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
};

export type TagMood = {
  _id: string;
  _type: "tag.mood";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
};

export type TagService = {
  _id: string;
  _type: "tag.service";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
};

export type TagMusician = {
  _id: string;
  _type: "tag.musician";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
};

export type TagVenue = {
  _id: string;
  _type: "tag.venue";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
  short?: string;
};

export type TagGlobal = {
  _id: string;
  _type: "tag.global";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
};

export type TagGenre = {
  _id: string;
  _type: "tag.genre";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
  subGenres?: Array<
    {
      _key: string;
    } & TagSubGenreReference
  >;
};

export type TagCity = {
  _id: string;
  _type: "tag.city";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: InternationalizedArrayString;
  short?: InternationalizedArrayString;
};

export type TagCrafts = {
  _id: string;
  _type: "tag.crafts";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
};

export type TagArticle = {
  _id: string;
  _type: "tag.article";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
};

export type CategorySub = {
  _id: string;
  _type: "category.sub";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
};

export type Category = {
  _id: string;
  _type: "category";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
  subCategories?: Array<
    {
      _key: string;
    } & CategorySubReference
  >;
};

export type Slug = {
  _type: "slug";
  current?: string;
  source?: string;
};

export type Soundcloud = {
  _type: "soundcloud";
  id?: number;
  created_at?: string;
  duration?: number;
  tag_list?: string;
  streamable?: boolean;
  purchase_url?: string;
  genre?: string;
  title?: string;
  description?: string;
  release_year?: number;
  release_month?: number;
  release_day?: number;
  license?: string;
  uri?: string;
  user?: User;
  artwork_url?: string;
  waveform_url?: string;
  stream_url?: string;
  playback_count?: number;
  favoritings_count?: number;
};

export type RgbaColor = {
  _type: "rgbaColor";
  r?: number;
  g?: number;
  b?: number;
  a?: number;
};

export type HsvaColor = {
  _type: "hsvaColor";
  h?: number;
  s?: number;
  v?: number;
  a?: number;
};

export type HslaColor = {
  _type: "hslaColor";
  h?: number;
  s?: number;
  l?: number;
  a?: number;
};

export type MuxVideoAsset = {
  _id: string;
  _type: "mux.videoAsset";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  status?: string;
  assetId?: string;
  playbackId?: string;
  filename?: string;
  thumbTime?: number;
  data?: MuxAssetData;
};

export type MuxAssetData = {
  _type: "mux.assetData";
  resolution_tier?: string;
  upload_id?: string;
  created_at?: string;
  id?: string;
  status?: string;
  max_stored_resolution?: string;
  passthrough?: string;
  encoding_tier?: string;
  video_quality?: string;
  master_access?: string;
  aspect_ratio?: string;
  duration?: number;
  max_stored_frame_rate?: number;
  mp4_support?: string;
  max_resolution_tier?: string;
  tracks?: Array<
    {
      _key: string;
    } & MuxTrack
  >;
  playback_ids?: Array<
    {
      _key: string;
    } & MuxPlaybackId
  >;
  static_renditions?: MuxStaticRenditions;
};

export type MuxStaticRenditions = {
  _type: "mux.staticRenditions";
  status?: string;
  files?: Array<
    {
      _key: string;
    } & MuxStaticRenditionFile
  >;
};

export type MuxStaticRenditionFile = {
  _type: "mux.staticRenditionFile";
  name?: string;
  ext?: string;
  height?: number;
  width?: number;
  bitrate?: number;
  filesize?: string;
  type?: string;
  status?: string;
  resolution_tier?: string;
  resolution?: string;
  id?: string;
  passthrough?: string;
};

export type MuxPlaybackId = {
  _type: "mux.playbackId";
  id?: string;
  policy?: string;
};

export type MuxTrack = {
  _type: "mux.track";
  id?: string;
  type?: string;
  max_width?: number;
  max_frame_rate?: number;
  duration?: number;
  max_height?: number;
  language_code?: string;
  name?: string;
  status?: string;
  text_source?: string;
  text_type?: string;
};

export type MediaTag = {
  _id: string;
  _type: "media.tag";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  name?: Slug;
};

export type SanityImagePaletteSwatch = {
  _type: "sanity.imagePaletteSwatch";
  background?: string;
  foreground?: string;
  population?: number;
  title?: string;
};

export type SanityImagePalette = {
  _type: "sanity.imagePalette";
  darkMuted?: SanityImagePaletteSwatch;
  lightVibrant?: SanityImagePaletteSwatch;
  darkVibrant?: SanityImagePaletteSwatch;
  vibrant?: SanityImagePaletteSwatch;
  dominant?: SanityImagePaletteSwatch;
  lightMuted?: SanityImagePaletteSwatch;
  muted?: SanityImagePaletteSwatch;
};

export type SanityImageDimensions = {
  _type: "sanity.imageDimensions";
  height?: number;
  width?: number;
  aspectRatio?: number;
};

export type SanityImageMetadata = {
  _type: "sanity.imageMetadata";
  location?: Geopoint;
  dimensions?: SanityImageDimensions;
  palette?: SanityImagePalette;
  lqip?: string;
  blurHash?: string;
  thumbHash?: string;
  hasAlpha?: boolean;
  isOpaque?: boolean;
};

export type SanityFileAsset = {
  _id: string;
  _type: "sanity.fileAsset";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  originalFilename?: string;
  label?: string;
  title?: string;
  description?: string;
  altText?: string;
  sha1hash?: string;
  extension?: string;
  mimeType?: string;
  size?: number;
  assetId?: string;
  uploadId?: string;
  path?: string;
  url?: string;
  source?: SanityAssetSourceData;
};

export type SanityAssetSourceData = {
  _type: "sanity.assetSourceData";
  name?: string;
  id?: string;
  url?: string;
};

export type SanityImageAsset = {
  _id: string;
  _type: "sanity.imageAsset";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  originalFilename?: string;
  label?: string;
  title?: string;
  description?: string;
  altText?: string;
  sha1hash?: string;
  extension?: string;
  mimeType?: string;
  size?: number;
  assetId?: string;
  uploadId?: string;
  path?: string;
  url?: string;
  metadata?: SanityImageMetadata;
  source?: SanityAssetSourceData;
};

export type Geopoint = {
  _type: "geopoint";
  lat?: number;
  lng?: number;
  alt?: number;
};

export type AllSanitySchemaTypes =
  | SanityFileAssetReference
  | LinkFile
  | VideoSettings
  | SlideVideoSettings
  | User
  | SanityImageAssetReference
  | Slide
  | SeoPage
  | SeoSingletons
  | SanityImageCrop
  | SanityImageHotspot
  | SeoFallback
  | PlaceholderString
  | ModuleText
  | ModuleMedia
  | ModuleHeroSlider
  | PersonReference
  | VenueReference
  | ShowReference
  | SetReference
  | ArticleReference
  | ModuleHeroEntry
  | ModuleContentReferenceSlider
  | ModuleContentReferenceGrid
  | ModuleCarousel
  | Modules
  | LinkFunctions
  | HomeReference
  | PoolReference
  | ShowsArchiveReference
  | TimetableReference
  | WordsReference
  | PageReference
  | CategoryReference
  | CategorySubReference
  | TagArticleReference
  | TagCraftsReference
  | TagCityReference
  | TagGenreReference
  | TagGlobalReference
  | TagVenueReference
  | TagMusicianReference
  | TagServiceReference
  | TagMoodReference
  | TagSubGenreReference
  | OptionalLink
  | Link
  | RichTextMedia
  | RichText
  | FallbackContentLocalized
  | FallbackContent
  | FallbackGlobal
  | InternationalizedArrayRichText
  | InternationalizedArrayString
  | SiteSettings
  | SiteNav
  | SiteCookieBanner
  | Code
  | Error
  | InternationalizedArrayRichTextMediaValue
  | InternationalizedArrayRichTextValue
  | InternationalizedArrayStringValue
  | InternationalizedArrayRichTextMedia
  | Home
  | Color
  | Pool
  | ShowsArchive
  | Timetable
  | Words
  | Person
  | Article
  | Page
  | Show
  | Set
  | MuxVideoAssetReference
  | MuxVideo
  | Venue
  | TagSubGenre
  | TagMood
  | TagService
  | TagMusician
  | TagVenue
  | TagGlobal
  | TagGenre
  | TagCity
  | TagCrafts
  | TagArticle
  | CategorySub
  | Category
  | Slug
  | Soundcloud
  | RgbaColor
  | HsvaColor
  | HslaColor
  | MuxVideoAsset
  | MuxAssetData
  | MuxStaticRenditions
  | MuxStaticRenditionFile
  | MuxPlaybackId
  | MuxTrack
  | MediaTag
  | SanityImagePaletteSwatch
  | SanityImagePalette
  | SanityImageDimensions
  | SanityImageMetadata
  | SanityFileAsset
  | SanityAssetSourceData
  | SanityImageAsset
  | Geopoint;
