name: Dependabot auto-merge

on:
  pull_request:
    branches: [main]

permissions:
  contents: write
  pull-requests: write

jobs:
  auto-merge:
    uses: Callshop-Radio/.github/.github/workflows/dependabot-auto-merge.yml@e3e58bbfc9a8acd262c5ea7d7b2579e928a06c7f
    secrets: inherit
